### ISSUE TITLE
[Specification] Update general documentation for Cyber and Liability

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ODS_OpenExposureData#206]
## Description

The documentation for Cyber and Liability needs to be reviewed and updated to reflect the integration into the main spec.

- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Liability/ReadMe.md (REVIEW/UPDATE)
- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Liability/Docs/ODS_Liabs_Rationale_Taxonomy_v1.0.pdf (REVIEW/UPDATE)
- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Liability/Docs/ODS_Liability_Taxonomy_v1.pdf (REVIEW/UPDATE)
- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Liability/Docs/OED_Liabs_DataFields.csv (REMOVE?)
- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Liability/Docs/OED_Liabs_DataSpec_v1.0.xlsx (REMOVE?)
- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Cyber/ReadMe.md (REVIEW/UPDATE)
- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Cyber/Docs/OED_Cyber_DataFields_v1.0.0.csv (REMOVE?)
- [x] https://github.com/OasisLMF/ODS_OpenExposureData/blob/release/4.0.0rc1/OpenExposureData/Cyber/Docs/OED_Cyber_Data_Spec_v1.0.0.xlsx (REMOVE?)

```[tasklist]
### Tasks
- [ ] Main README (REVIEW/UPDATE)
```

**Comment by MattDonovan82** [comment]
@johcarter I agree with removing the suggested v1 specs for cyber and liability. In regards to reviewing the current documentation, where is best to do this? As discussed, the updating of the documentation for cyber and liability will likely occur during the three month RC release window. So is the RC branch the best place to update documentation?

**Comment by johcarter** [comment]
Thanks @MattDonovan82 , I suggest waiting until after the repo restructure and final release candidate is ready, and then perhaps branching off that for the documentation updates. @sambles might also have a view on how best to go about this.

**Comment by MattDonovan82** [comment]
This is on my list for the next couple of weeks. Do you think we still need the pdf docs? If the 'read me' get updated these pdf seem unnecessary? @johcarter
